name: Terraform Static Analysis

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Install TFLint
        run: |
          curl -LO https://github.com/terraform-linters/tflint/releases/download/v0.35.0/tflint-linux-amd64.zip
          unzip tflint-linux-amd64.zip
          sudo mv tflint /usr/local/bin/

      - name: Run TFLint
        run: tflint infra/tf-app/
