name: Terraform Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init infra/tf-app

      - name: Terraform Plan
        run: terraform plan -out=tfplan infra/tf-app

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
